#!/bin/bash
#SBATCH --job-name=slurm
#SBATCH -a 1       
#SBATCH --ntasks=1 --nodes=1
#SBATCH --mail-user=twesleyb10@gmail.com --mail-type=END  
#SBATCH -e ./out/job_%j.err
#SBATCH -o ./out/job_%j.out 
#SBATCH -c 18
#SBATCH --mem=16G      
#SBATCH -p scavenger

# Get filename and extension of input script.
filename=$1
extension=${filename##*\.} 

# Appropriately execute python or R script. 
if [ $extension == "py" ]
then
	module load Python/3.6.4 
	./$filename
elif [ $extension == "R" ]
then
	module load R/3.6.0
	./$filename
else
	echo "$extension files are not currently supported!"
fi
